Repository projetoKhali/api3, pull requests merged in 2023-11, with the labels that each got.

#174 feat: troca de senha para usuario
  api/src/main/java/com/khali/api3/controllers/UserController.java
  api/src/main/java/com/khali/api3/domain/permission/Permission.java
  web/src/App.tsx
  web/src/components/ChangePasswordForm.tsx
  web/src/services/Access.ts
  web/src/services/UserService.ts
Labels: User, Back End, Front End, Endpoint

#185 Correção de bugs
  api/src/main/java/com/khali/api3/controllers/AppointmentController.java
  api/src/main/java/com/khali/api3/domain/notification/Notification.java
  api/src/main/java/com/khali/api3/repositories/AppointmentRepository.java
Labels: bug, Back End, Front End, Entity, repository

#177 feat: Identificação de dias da semana na verba
  api/sql/ddl/data.sql
  api/sql/ddl/table.sql
  api/src/main/java/com/khali/api3/Api3Application.java
  api/src/main/java/com/khali/api3/config/JpaConfig.java
  api/src/main/java/com/khali/api3/controllers/AppointmentController.java
  api/src/main/java/com/khali/api3/controllers/ParameterController.java
  api/src/main/java/com/khali/api3/controllers/PayRateRuleController.java
  api/src/main/java/com/khali/api3/converters/days_of_week/DaysOfWeekConverter.java
  api/src/main/java/com/khali/api3/domain/pay_rate_rule/PayRateRule.java
  api/src/main/java/com/khali/api3/domain/pay_rate_rule/Shift.java
  api/src/main/java/com/khali/api3/domain/pay_rate_rule/Week.java
  api/src/main/java/com/khali/api3/repositories/AppointmentRepository.java
  api/src/main/java/com/khali/api3/repositories/ParametersRepository.java
  api/src/main/java/com/khali/api3/repositories/PayRateRuleRepository.java
  api/src/main/java/com/khali/api3/services/AppointmentService.java
  api/src/main/java/com/khali/api3/services/PayRateRuleService.java
  web/src/App.tsx
  web/src/services/ParametrizationService.ts
Labels: Update, Back End, Front End, database, param

#184 feat: <Componentes UX> Criação da mensagens e filtros
  api/pom.xml
  api/src/main/java/com/khali/api3/controllers/AppointmentController.java
  web/src/components/AppointmentForm.tsx
  web/src/components/ClientForm.tsx
  web/src/components/Filter.tsx
  web/src/components/PopUpMessage.tsx
  web/src/components/PopupForm.tsx
  web/src/components/ProjectForm.tsx
  web/src/components/ResultCenterForm.tsx
  web/src/components/UserForm.tsx
  web/src/pages/AdmAppointments.tsx
  web/src/pages/ManagerAppointments.tsx
  web/src/pages/UserAppointments.tsx
  web/src/pages/Users.tsx
  web/src/services/AppointmentService.ts
  web/src/services/ClientService.ts
  web/src/services/PayRateRulesService.ts
  web/src/services/ProjectService.ts
  web/src/services/UserService.ts
Labels: Update, enhancement, Front End

#193 fix: Ajustes no README e Appointments
  Docs/burndown/Sprint1.jpg
  Docs/burndown/Sprint2.jpg
  README.md
  api/src/main/java/com/khali/api3/controllers/AppointmentController.java
  api/src/main/java/com/khali/api3/repositories/AppointmentRepository.java
  docs/burndown/sprint_2.png
  web/src/components/AppointmentForm.tsx
Labels: documentation

#194 Fix notification
  api/src/main/resources/db/migration/V3__update_pay_rate_table.sql
  api/src/main/resources/db/migration/V4_create_notification.sql
  web/src/components/AppointmentForm.tsx
Labels: Front End

#186 Feat: <Cryptography.java> Criando método de criptografia
  api/src/main/java/com/khali/api3/controllers/UserController.java
  api/src/main/java/com/khali/api3/domain/user/Cryptography.java
  api/src/main/resources/db/migration/V4__create_notifications_table.sql
Labels: User, Back End, Endpoint

#205 fix: `pairLocalTimeToTimestamp` merge bug
  api/src/main/java/com/khali/api3/controllers/SliceController.java
Labels: bug, report

#199 Css
  api/sql/ddl/data.sql
  api/src/main/java/com/khali/api3/domain/util/Pair.java
  api/src/main/java/com/khali/api3/repositories/AppointmentRepository.java
  api/src/main/java/com/khali/api3/repositories/PayRateRuleRepository.java
  api/src/main/java/com/khali/api3/services/PayRateRuleService.java
  pgconnect.sh
  test_api.sh
  web/index.html
  web/public/khali_logo_dark.png
  web/public/khali_logo_light.png
  web/src/App.tsx
  web/src/components/AppointmentForm.tsx
  web/src/components/Dropdown.tsx
  web/src/components/LookUpTextField.tsx
  web/src/components/PopUp.tsx
  web/src/components/SideMenu.tsx
  web/src/index.css
  web/src/main.tsx
  web/src/pages/Login.tsx
  web/src/styles/App.css
  web/src/styles/appointment-form.css
  web/src/styles/dropdown.css
  web/src/styles/form.css
  web/src/styles/index.css
  web/src/styles/login.css
  web/src/styles/lookup-text-field.css
  web/src/styles/menuStyle.css
  web/src/styles/popup.css
  web/src/styles/userTData.css
Labels: Front End
